version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "33063:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=projeto
    volumes:
      - ./dbdata:/var/lib/mysql
volumes:
  dbdata: